spring:
    resources:
        static-locations: classpath:/
    jpa:
        show-sql: true
    aop:
        auto: true
    profiles:
            active: dev

server:
    port: 84

logging:
    config: classpath:logback/logback-spring.xml

